config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "songs#index"
  devise_for :users
   
  resources :songs

  get "up" => "rails/health#show", as: :rails_health_check

resources :songs do
  collection do
    get :search
  end
end

  resources :songs do
    member do
      patch :publish
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable,
         :trackable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at", "current_sign_in_at", "sign_in_count"]
  end
end

app/models/album.rb
class Album < ApplicationRecord
  before_validation :set_default_title
  
  def set_default_title
    self.title ||= "Untitled Album"
  end


    has_rich_text :content
    has_one_attached :profile_image
    belongs_to:user
    has_one_attached:audio
    has_many :taggings 
    has_many :tags, through: :taggings
    attribute :published, :boolean, default: false
    scope :published, -> { where(published: true) }

  
       def all_tags=(names)
        self.tags = names.split(",").map do |name|
          Tag.where(name: name.strip).first_or_create!
        end
      end
                  
      def all_tags
        self.tags.map(&:name).join(", ")
      end

      def self.ransackable_associations(auth_object = nil)
        ["tags"]
      end
    
      def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "price", "title", "updated_at"]
      end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
  before_validation :set_default_title

  def set_default_title
    self.title ||= "Untitled Song"
  end

  has_rich_text :content
  has_one_attached :profile_image
  belongs_to :user
  has_one_attached :audio
  has_many :taggings
  has_many :tags, through: :taggings
  attribute :published, :boolean, default: false
  scope :published, -> { where(published: true) }

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.ransackable_associations(auth_object = nil)
    ["tags", "user"] # Added "user" to make related search possible
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "title", "updated_at", "published", "user_id"]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
has_many :taggings
has_many :songs, through: :taggings

def self.ransackable_attributes(auth_object = nil)
  [
    "name"
  ]
end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
    belongs_to :song
    belongs_to :tag
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   has_many :songs
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_associations(auth_object = nil)
    ["songs"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!  
    include Devise::Controllers::Helpers
  end
  

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update destroy]
  before_action :set_song, only: %i[show edit update destroy]
  before_action :set_search

  # GET /songs or /songs.json
  def index
    @q = Song.ransack(params[:q])
    @songs = @q.result(distinct: true).includes(:tags).where(published: true) # Include associated tags to avoid N+1 queries
  end

  def new
    @song = current_user.songs.build
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = current_user.songs.build(song_params)
    @song.published = params[:song][:published] == '1'

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @q = Song.ransack(params[:q])
    @songs = @q.result(distinct: true)
    render :index
  end

  def publish
    @song = current_user.songs.find(params[:id])
    @song.update(published: true)
    redirect_to songs_path, notice: 'Song published successfully.'
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.taggings.destroy_all
    @song.destroy

    # Destroy associated rich text content

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_description }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def song_params
    params.require(:song).permit(:title, :description, :published, :price, :all_tags, :audio, :profile_image)
  end

  def set_search
    @q = Song.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/albums/_form.html.erb
<%= form_with(model: album ,local:true) do |form| %> <% if album.errors.any? %>
<div style="color: red">
  <h2>
    <%= pluralize(album.errors.count, "error") %> prohibited this album from
    being saved:
  </h2>

  <ul>
    <% album.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div>
  <%= form.label :title, style: "display: block " %> <%= form.text_field :title%>
</div>

<div>
  <%= form.label :description, style: "display: block" %> <%= form.text_area:description %>
</div>

<div class="form-group m-2">
  <%= form.label :profile_image %><br />
  <%= form.file_field :profile_image %>
</div>

<div class="form-group m-2">
  <%= form.label :audio %><br/>
  <%= form.file_field :audio %>
</div>

<div class="field m-2">
  <%= form.label :tags ,style:"display: block;" %> <%= form.text_field :all_tags
  %>
  <!-- Assuming a comma-separated list of tags -->
</div>

<div class="m-2">
  <%= form.label :price, style: "display: block ;" %>
  <%= form.number_field :price %>
</div>


<div class="field m-2">
  <%= form.label :published %> <%= form.check_box :published %>
</div>

<div><%= form.submit "Submit", class: "btn btn-info" %></div>

<% end %>

app/views/albums/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <%= f.label :tags_name_cont, "Tag" %>
    <%= f.search_field :tags_name_cont %>
    <%= f.submit "Search" , class:"mt-2 btn btn-info",style:"margin-left:150px;" %>
 <% end %>

app/views/albums/edit.html.erb
<div class="edit container-fluid mt-4 d-flex" style="color: orange">
  <%= render "form", album: @album %>

  <br />
</div>

<div class="mt-4"><%= link_to "Show this album", @album %></div>

app/views/albums/index.html.erb
<div class="container-fluid">
  <br />
  <div class="" autocomplete="off" id="search-form" style="margin-left: 900px">
    <%= render 'albums/search_form' %>
  </div>
  <div class="row">
    <h4
      id="al"
      class="mt-4 mb-4 display-5 text-center"
      style="
        background-color: white;
        margin-left: -20px;
        color: rgb(30, 215, 96);
      "
    >
      Albums
    </h4>
  </div>

  <div id="card" class="container-fluid bg-white">
    <div class="row">
      <% @albums.each do |album| %>

      <div class="col-md-3 col-sm-12 mb-4">
        <div class="card m-2" style="height: 180px; border: none">
          <div class="card1">
            <%= image_tag 'carousel2.jpg', class: 'card-img-top img-fluid',
            style: 'max-height: 350px;width:200px' %>
            <h5
              class="card-title text-center mt-4"
              style="text-decoration: none; margin-left: -200px"
            >
              <%= link_to album.title, album %>
              
            </h5>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/new.html.erb
<div class="container-fluid m-4 d-flex" style="color:blue">
    <%= render "form", album: @album %>
    <br>
</div>

app/views/albums/show.html.erb
<div
  class="container-fluid show d-flex"
  style="padding-left: 250px; padding-top: 100px"
>
  <p style="color: red"><%= notice %></p>
  <div class="d-flex"><%= render @album %></div>
  <div>
    <br />
    <div style="margin-left: 100px; ">
      <% if @album.profile_image.present? %> <%= image_tag @album.profile_image,
      width: 250, height: 300, resize_to_fill: [100, 100] %> <% else %>
      <!-- Provide a default image or a placeholder if the profile_image is not present -->
      <%= image_tag '', width: 250, height: 300, resize_to_fill: [100, 100] %>
      <% end %>

      <br />
      <br />

    <br/>
  <%= audio_tag @album.audio, controls: true %>
    
    </div>
    <br />
    <div class="mt-3 " style="margin-left:170px">
      <h2>Your Albums</h2>
      <% current_user.albums.each do |album| %>
      <p><%= link_to album.title, album_path(album) %></p>
      <% end %>
      
    </div>
  </div>
</div>

<div style="margin-left: 250px">
  <%= link_to "Edit this album", edit_album_path(@album) %>
  <br />
  <br />
  <%= button_to "Destroy this album", @album, method: :delete,class:"btn
  btn-danger" %>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" style="margin-top:60px ;">
  <div class="footer-top bg-dark" style="color:white;">
    <div class="container-fluid d-flex " style="">
      <div class="row row1 ml-5" >

        <div class="col-lg-3 col-md-3 footer-links mt-2 col-4">
          <h4>About Us</h4>
          <p>Lorem ipsum dolor! Laborum consequatur, ducimus animi ea, quibusdam maxime asperiores exercitationem.</p>
        </div>

        <div class="col-lg-3 col-md-3 footer-links mt-2 ml-5 col-4" style="padding-left:250px">
          <h4 class="navigation text-center">Navigation Links</h4>
          <div class="row navigationlist">
            <div class = "col-sm-6">
              <ul class="list_style list1">
                <li><a>Home</a></li>
                <li><a>Feature</a></li>
                <li><a>Services</a></li>
                <li><a>Portfolio</a></li>
              </ul>
            </div>


          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 footer-links d-flex mt-2 ml-5 col-4" style="padding-left:500px">
          <div class ="link3">
            <h4>News Letter</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, ad?</p>
            <div class="email-form d-flex flex-row">

            </div>

          </div>

        </div>
      </div>
    </div>

    <div class="container-fluid py-4 footer-bottom">
      <div class="copyright text-center">
        &copy; Copyright KS32</strong>.All Rights Reserved
      </div
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark"  >
  <div class="container-fluid" >
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <li class="nav-item px-3" style="font-size:small;">
          <%= link_to "Songs", songs_path, class: "nav-link text-capitalize fs-5",style:"color:white" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item" style="color:white">
            <%= link_to "New song", new_song_path, class: "nav-link text-capitalize fs-5", style: "color:white" %>
          </li>
        <% end %>


        <% if user_signed_in? %>
          <li class="nav-item px-3">
            <%= link_to "edit profile", edit_user_registration_path, class: 'nav-link text-capitalize fs-5 ',style:"color:white"%>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Sign Out", destroy_user_session_path, class: 'nav-link text-capitalize fs-5', style:"color:white",data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item px-3">
            <%= link_to "sign up", new_user_registration_path, class: 'nav-link text-capitalize fs-5',style:"color:white" %>
          </li>
          <li class="nav-item px-3">
            <%= link_to "Login", new_user_session_path, class: 'nav-link text-capitalize fs-5',style:"color:white" %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex align-items-center">
        <% if user_signed_in? %>
          <i class="fa-solid fa-user me-2 px-2" style=" color:lightblack;"></i>
          <a href="#" style="color: white; text-decoration: none;"><%= current_user.email %></a>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  
  </head>

  <body>

  <%= render 'layouts/header' %>

  <div class="container-fluid">  
    <%= yield %>
    </div>

  <div  >
  
  </div>

  
    


    


<p class="alert"><%= alert %></p>




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>




<%= render 'layouts/footer' %>
</body>
</html>

app/views/songs/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Song Information</div>
        <div class="card-body">
          <%= form_with(model: song, local: true, class: "form-horizontal") do |form| %>
            <% if song.errors.any? %>
              <div class="alert alert-danger">
                <h2><%= pluralize(song.errors.count, "error") %> prevent this song from being saved:</h2>
                <ul>
                  <% song.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :title, "Title", class: "control-label" %>
              <%= form.text_field :title, class: "form-control", placeholder: "Enter title" %>
            </div>

            <div class="form-group">
              <%= form.label :description, "Description", class: "control-label" %>
              <%= form.text_area :description, class: "form-control", placeholder: "Enter description" %>
            </div>

            <div class="form-group">
              <%= form.label :profile_image, "Profile Image", class: "control-label" %>
              <%= form.file_field :profile_image, class: "form-control-file" %>
            </div>

            <div class="form-group">
              <%= form.label :audio, "Audio", class: "control-label" %>
              <%= form.file_field :audio, class: "form-control-file" %>
            </div>

            <div class="form-group">
              <%= form.label :tags, "Tags", class: "control-label" %>
              <%= form.text_field :all_tags, class: "form-control", placeholder: "Enter tags" %>
            </div>

            <div class="form-group form-check">
              <%= form.check_box :published, class: "form-check-input" %>
              <%= form.label :published, "Published", class: "form-check-label" %>
            </div>

            <div class="form-group">
              <%= form.submit "Submit", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/songs/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :tags_name_cont, "Tag" %>
  <%= f.search_field :tags_name_cont %>
  <%= f.submit "Search" , class: "mt-2 btn btn-info",style: "margin-left:150px;" %>
<% end %>

app/views/songs/_song.html.erb
<div style="color:purple; margin-top:80px" id="<%= dom_id song %>">
  <p>
    <strong>Title:</strong>
    <%= song.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= song.description %>
  </p>

  <p>
    <strong>Tag:</strong>
    <%= song.all_tags %>
  </p>
</div>

app/views/songs/edit.html.erb
<div class="edit container-fluid mt-4 d-flex justify-content-center" style="color: orange">
  <%= render "form", song: @song %>
</div>

<div class="mt-4 text-center">
  <%= link_to "Show this song", @song, class: "btn btn-primary", style: "color: black; text-decoration: none;" %>
</div>

app/views/songs/index.html.erb
<div class="container-fluid">
  <br />
  <div class="" autocomplete="off" id="search-form" style="margin-left: 900px">
    <%= render 'songs/search_form' %>
  </div>
  <div class="row">
    <h4
      id="al"
      class="mt-4 mb-4 display-5 text-center"
      style="
      background-color: white;
        margin-left: -20px;
        color: rgb(30, 215, 96);
      "
    >
      Songs
    </h4>
  </div>

  <div id="card" class="container-fluid bg-white">
    <div class="row">
      <% @songs.each do |song| %>
        <div class="col-md-3 col-sm-12 mb-4">
          <div class="card m-2" style="height: 180px; border: none">
            <div class="card1">
              <%= image_tag 'carousel2.jpg', class: 'card-img-top img-fluid', style: 'max-height: 350px;width:200px' %>
              <h5 class="card-title text-center mt-4" style="text-decoration: none; margin-left: -200px">
                <%= link_to song.title, song %>
              </h5>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/songs/new.html.erb
<div class="container-fluid m-4 d-flex" style="color:blue">
  <%= render "form", song: @song %>
  <br>
</div>

app/views/songs/show.html.erb
<div class="container-fluid show d-flex flex-column align-items-center" style="padding-top: 100px; background-color: #f8f9fa; color: #333; min-height: 100vh;">
  <p style="color: red;"><%= notice %></p>

  <div class="d-flex flex-row align-items-start shadow p-3 mb-5 bg-white rounded">
    <div class="d-flex flex-column align-items-center">
      <% if @song.profile_image.present? %>
        <%= image_tag @song.profile_image, class: "img-thumbnail rounded-circle shadow", style: "width: 250px; height: 250px; object-fit: cover;" %>
      <% else %>
        <%= image_tag 'default_image_path', class: "img-thumbnail rounded-circle shadow", style: "width: 250px; height: 250px; object-fit: cover;" %>
      <% end %>

      <div class="mt-3">
        <%= audio_tag @song.audio, controls: true, class: "audio-player" %>
      </div>
    </div>

    <div class="ml-4 p-3 bg-light shadow-sm rounded" style="max-width: 400px; border: 1px solid #ccc; color: #333;">
      <%= render @song %>
    </div>
  </div>

  <div class="container mt-5 w-25">
    <h2 class="text-center mb-4">Your Songs</h2>
    <div class="list-group">
      <% current_user.songs.each do |song| %>
        <div class="list-group-item list-group-item-action bg-white text-dark border-0 shadow-sm mb-2 rounded">
          <div class="d-flex justify-content-between align-items-center">
            <span><%= song.title %></span>
            <%= link_to song_path(song), class: "btn btn-sm btn-success text-white", method: :get do %>
              View
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-3 d-flex justify-content-center">
    <%= link_to edit_song_path(@song), class: "btn btn-primary mx-2 shadow text-white", style: "text-decoration: none; background-color: #198754; border-color: #198754;" do %>
      Edit this song
    <% end %>
    <%= button_to @song, method: :delete, class: "btn btn-danger mx-2 shadow text-white", style: "text-decoration: none; background-color: #dc3545; border-color: #000000;" do %>
      Destroy this song
    <% end %>
  </div>


</div>